### ISSUE TITLE
Why was the license stripped out?

### ISSUE THREAD

**Issue by clayrisser** [creationix/node-gir#44]
Just curious, but some portions of this code was licensed under GPL2, and the license was stripped out. I think that’s technically a license breach. Any particular reason the license was removed?

https://github.com/GNOME/gnode/blob/master/src/loop.cc

**Comment by clayrisser** [comment]
I don’t think you can license a project using GPL under the MIT license.

**Comment by Place1** [comment]
@jamrizzi This repo never included that code, I added it to my fork after finding it in https://github.com/WebReflection/node-gtk/blob/master/src/loop.cc

I think you meant to post this issue to that project (WebReflection), not creationix's project?

**Comment by clayrisser** [comment]
Oh dear, my bad
